site:
  title: My Project Documentation
  start_page: ROOT:index 
  url: https://docs.myproject.com

content:
  sources:
    - url: https://github.com/sshkodrov/repo1.git
      start_page: docs
      branches: master

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable

output:
  dir: ./build        
