name: Deploy Antora Documentation to GitHub Pages

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Set up JDK 11 (Zulu)
      #   uses: actions/setup-java@v2
      #   with:
      #     distribution: 'zulu'
      #     java-version: '11'

      # - name: Install Antora
      #   run: |
      #     curl -L https://github.com/antora/antora/releases/download/3.1.9/antora-3.1.9.tar.gz
      #     sudo mv antora-3.1.9/bin/antora /usr/local/bin

      - name: Build the documentation site
        run: | 
            antora generate antora.yml --stacktrace
      - name: List build directory contents
        run: |
            ls -R ./build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.MY_ANTORA_TOKEN }}
          publish_dir: ./build
          publish_branch: origin/master
